name: Build and Save Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-save-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t my-image .

      - name: Save Docker image to file
        run: docker save my-image -o my-image.tar

      - name: Upload image artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-image
          path: my-image.tar
