name: build docker
on:
  push:
    branches:
      - 'main'
jobs:
  build-and-push:
    name: build and push
    runs-on: ubuntu-latest
    steps:
      - name: check code
        uses: actions/checkout@v4
        
      - name: go to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      - name: push and build docker image to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: v1lou/image:latest
