name: docker-build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: repository
      uses: actions/checkout@v2

    - name: docker image
      run: docker build -t docker-image:latest .

    - name: save image
      run: docker save -o docker-image.image docker-image:latest

    - name: charge image
      uses: actions/upload-artifact@v2
      with:
        name: docker-image
        path: docker-image.image
